
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Jul  3 2026 23:53:34 +07 (Jul  3 2026 16:53:34 UTC)

// Verification Directory fv/spi 

module spi(clk, reset, ssn, sck, sdi, sdo, addr, data_w, en_write,
     data_r, en_read);
  input clk, reset, ssn, sck, sdi;
  input [7:0] data_r;
  output sdo, en_write, en_read;
  output [6:0] addr;
  output [7:0] data_w;
  wire clk, reset, ssn, sck, sdi;
  wire [7:0] data_r;
  wire sdo, en_write, en_read;
  wire [6:0] addr;
  wire [7:0] data_w;
  wire [4:0] counter;
  wire [7:0] shift_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_52, n_53, n_54, n_55, n_69, rw_bit;
  wire sck_prev;
  DFCNQD1 \addr_reg[0] (.CDN (n_55), .CP (clk), .D (n_48), .Q
       (addr[0]));
  DFCNQD1 \addr_reg[6] (.CDN (n_55), .CP (clk), .D (n_50), .Q
       (addr[6]));
  DFCNQD1 \addr_reg[5] (.CDN (n_55), .CP (clk), .D (n_54), .Q
       (addr[5]));
  DFCNQD1 \addr_reg[3] (.CDN (n_55), .CP (clk), .D (n_53), .Q
       (addr[3]));
  DFCNQD1 \addr_reg[1] (.CDN (n_55), .CP (clk), .D (n_46), .Q
       (addr[1]));
  DFCNQD1 \addr_reg[4] (.CDN (n_55), .CP (clk), .D (n_49), .Q
       (addr[4]));
  DFCNQD1 \addr_reg[2] (.CDN (n_55), .CP (clk), .D (n_47), .Q
       (addr[2]));
  DFCNQD1 \counter_reg[4] (.CDN (n_55), .CP (clk), .D (n_45), .Q
       (counter[4]));
  AO22D0 g1683__2398(.A1 (n_52), .A2 (data_w[4]), .B1 (addr[5]), .B2
       (n_69), .Z (n_54));
  AO22D0 g1690__5107(.A1 (n_52), .A2 (data_w[2]), .B1 (addr[3]), .B2
       (n_69), .Z (n_53));
  AO22D0 g1689__6260(.A1 (n_52), .A2 (data_w[5]), .B1 (addr[6]), .B2
       (n_69), .Z (n_50));
  AO22D0 g1691__4319(.A1 (n_52), .A2 (data_w[3]), .B1 (addr[4]), .B2
       (n_69), .Z (n_49));
  AO22D0 g1686__8428(.A1 (n_52), .A2 (sdi), .B1 (addr[0]), .B2 (n_69),
       .Z (n_48));
  DFCNQD1 en_write_reg(.CDN (n_55), .CP (clk), .D (n_44), .Q
       (en_write));
  AO22D0 g1687__5526(.A1 (n_52), .A2 (data_w[1]), .B1 (addr[2]), .B2
       (n_69), .Z (n_47));
  AO22D0 g1688__6783(.A1 (n_52), .A2 (data_w[0]), .B1 (addr[1]), .B2
       (n_69), .Z (n_46));
  DFCNQD1 en_read_reg(.CDN (n_55), .CP (clk), .D (n_41), .Q (en_read));
  DFCNQD1 \counter_reg[3] (.CDN (n_55), .CP (clk), .D (n_42), .Q
       (counter[3]));
  AOI21D0 g1672__3680(.A1 (n_27), .A2 (n_43), .B (ssn), .ZN (n_45));
  NR2D0 g1694__1617(.A1 (n_43), .A2 (rw_bit), .ZN (n_44));
  NR2D0 g1678__2802(.A1 (n_32), .A2 (ssn), .ZN (n_42));
  NR2D0 g1692__1705(.A1 (n_69), .A2 (n_15), .ZN (n_41));
  DFCNQD1 \shift_out_reg[5] (.CDN (n_55), .CP (clk), .D (n_35), .Q
       (shift_out[5]));
  DFCNQD1 \shift_out_reg[1] (.CDN (n_55), .CP (clk), .D (n_31), .Q
       (shift_out[1]));
  DFCNQD1 \shift_out_reg[4] (.CDN (n_55), .CP (clk), .D (n_34), .Q
       (shift_out[4]));
  DFCNQD1 \shift_out_reg[2] (.CDN (n_55), .CP (clk), .D (n_39), .Q
       (shift_out[2]));
  DFCNQD1 \shift_out_reg[3] (.CDN (n_55), .CP (clk), .D (n_33), .Q
       (shift_out[3]));
  DFCNQD1 \shift_out_reg[7] (.CDN (n_55), .CP (clk), .D (n_28), .Q
       (sdo));
  DFCNQD1 \shift_out_reg[6] (.CDN (n_55), .CP (clk), .D (n_40), .Q
       (shift_out[6]));
  DFCNQD1 \counter_reg[2] (.CDN (n_55), .CP (clk), .D (n_30), .Q
       (counter[2]));
  CKND0 g1696(.I (n_69), .ZN (n_52));
  AO222D0 g1716__5122(.A1 (n_38), .A2 (shift_out[5]), .B1 (n_37), .B2
       (data_r[6]), .C1 (n_36), .C2 (shift_out[6]), .Z (n_40));
  AO222D0 g1711__8246(.A1 (n_38), .A2 (shift_out[1]), .B1 (n_37), .B2
       (data_r[2]), .C1 (n_36), .C2 (shift_out[2]), .Z (n_39));
  AO222D0 g1713__7098(.A1 (n_38), .A2 (shift_out[4]), .B1 (n_37), .B2
       (data_r[5]), .C1 (n_36), .C2 (shift_out[5]), .Z (n_35));
  AO222D0 g1714__6131(.A1 (n_38), .A2 (shift_out[3]), .B1 (n_37), .B2
       (data_r[4]), .C1 (n_36), .C2 (shift_out[4]), .Z (n_34));
  AO222D0 g1715__1881(.A1 (n_38), .A2 (shift_out[2]), .B1 (n_37), .B2
       (data_r[3]), .C1 (n_36), .C2 (shift_out[3]), .Z (n_33));
  MUX2ND0 g1695__5115(.I0 (n_26), .I1 (counter[3]), .S (n_29), .ZN
       (n_32));
  AO222D0 g1709__7482(.A1 (n_38), .A2 (shift_out[0]), .B1 (n_37), .B2
       (data_r[1]), .C1 (n_36), .C2 (shift_out[1]), .Z (n_31));
  OA211D0 g1698__4733(.A1 (counter[2]), .A2 (n_24), .B (n_29), .C
       (n_18), .Z (n_30));
  AO222D0 g1717__6161(.A1 (n_38), .A2 (shift_out[6]), .B1 (n_37), .B2
       (data_r[7]), .C1 (n_36), .C2 (sdo), .Z (n_28));
  OAI21D0 g1679__9315(.A1 (n_29), .A2 (n_26), .B (counter[4]), .ZN
       (n_27));
  OR3D0 g1699__9945(.A1 (counter[4]), .A2 (n_26), .A3 (n_29), .Z
       (n_43));
  DFCNQD1 \counter_reg[1] (.CDN (n_55), .CP (clk), .D (n_25), .Q
       (counter[1]));
  DFCNQD1 rw_bit_reg(.CDN (n_55), .CP (clk), .D (n_22), .Q (rw_bit));
  DFCNQD1 \shift_out_reg[0] (.CDN (n_55), .CP (clk), .D (n_21), .Q
       (shift_out[0]));
  AOI211D0 g1710__2346(.A1 (n_19), .A2 (n_4), .B (n_24), .C (ssn), .ZN
       (n_25));
  DFCNQD1 \counter_reg[0] (.CDN (n_55), .CP (clk), .D (n_20), .Q
       (counter[0]));
  MOAI22D0 g1725__1666(.A1 (n_17), .A2 (ssn), .B1 (n_16), .B2 (sdi),
       .ZN (n_22));
  AO22D0 g1720__7410(.A1 (n_37), .A2 (data_r[0]), .B1 (shift_out[0]),
       .B2 (n_36), .Z (n_21));
  DFCNQD1 \shift_in_reg[6] (.CDN (n_55), .CP (clk), .D (n_12), .Q
       (data_w[6]));
  DFCNQD1 \shift_in_reg[3] (.CDN (n_55), .CP (clk), .D (n_8), .Q
       (data_w[3]));
  DFCNQD1 \shift_in_reg[5] (.CDN (n_55), .CP (clk), .D (n_14), .Q
       (data_w[5]));
  CKND2D0 g1712__6417(.A1 (n_24), .A2 (counter[2]), .ZN (n_29));
  DFCNQD1 \shift_in_reg[7] (.CDN (n_55), .CP (clk), .D (n_10), .Q
       (data_w[7]));
  DFCNQD1 \shift_in_reg[4] (.CDN (n_55), .CP (clk), .D (n_5), .Q
       (data_w[4]));
  DFCNQD1 \shift_in_reg[2] (.CDN (n_55), .CP (clk), .D (n_7), .Q
       (data_w[2]));
  DFCNQD1 \shift_in_reg[1] (.CDN (n_55), .CP (clk), .D (n_9), .Q
       (data_w[1]));
  DFCNQD1 \shift_in_reg[0] (.CDN (n_55), .CP (clk), .D (n_6), .Q
       (data_w[0]));
  NR2D0 g1723__5477(.A1 (n_37), .A2 (n_36), .ZN (n_38));
  OA211D0 g1724__2398(.A1 (counter[0]), .A2 (n_13), .B (n_19), .C
       (n_18), .Z (n_20));
  OR2D0 g1737__5107(.A1 (n_16), .A2 (n_15), .Z (n_17));
  AO22D0 g1736__6260(.A1 (n_13), .A2 (data_w[4]), .B1 (data_w[5]), .B2
       (n_11), .Z (n_14));
  AO22D0 g1735__4319(.A1 (n_13), .A2 (data_w[5]), .B1 (data_w[6]), .B2
       (n_11), .Z (n_12));
  AO22D0 g1738__8428(.A1 (n_13), .A2 (data_w[6]), .B1 (data_w[7]), .B2
       (n_11), .Z (n_10));
  AO22D0 g1739__5526(.A1 (n_13), .A2 (data_w[0]), .B1 (data_w[1]), .B2
       (n_11), .Z (n_9));
  AO22D0 g1742__6783(.A1 (n_13), .A2 (data_w[2]), .B1 (data_w[3]), .B2
       (n_11), .Z (n_8));
  AO22D0 g1741__3680(.A1 (n_13), .A2 (data_w[1]), .B1 (data_w[2]), .B2
       (n_11), .Z (n_7));
  AO22D0 g1740__1617(.A1 (n_13), .A2 (sdi), .B1 (data_w[0]), .B2
       (n_11), .Z (n_6));
  AO22D0 g1743__2802(.A1 (n_13), .A2 (data_w[3]), .B1 (data_w[4]), .B2
       (n_11), .Z (n_5));
  NR2D0 g1722__1705(.A1 (n_19), .A2 (n_4), .ZN (n_24));
  NR4D0 g1734__5122(.A1 (n_2), .A2 (n_26), .A3 (n_15), .A4 (sck), .ZN
       (n_37));
  CKND2D0 g1744__8246(.A1 (n_13), .A2 (counter[0]), .ZN (n_19));
  AN3D1 g1745__7098(.A1 (n_13), .A2 (n_1), .A3 (n_3), .Z (n_16));
  INVD0 g1748(.I (n_13), .ZN (n_11));
  IIND4D0 g1746__6131(.A1 (n_3), .A2 (sck), .B1 (sck_prev), .B2
       (rw_bit), .ZN (n_36));
  IND3D0 g1747__1881(.A1 (counter[4]), .B1 (sck_prev), .B2 (n_1), .ZN
       (n_2));
  INR3D0 g1749__5115(.A1 (sck), .B1 (ssn), .B2 (sck_prev), .ZN (n_13));
  DFCNQD1 sck_prev_reg(.CDN (n_55), .CP (clk), .D (n_0), .Q (sck_prev));
  CKAN2D1 g1753__7482(.A1 (n_18), .A2 (sck), .Z (n_0));
  NR3D0 g1751__4733(.A1 (counter[0]), .A2 (counter[1]), .A3
       (counter[2]), .ZN (n_1));
  NR2D0 g1752__6161(.A1 (counter[4]), .A2 (counter[3]), .ZN (n_3));
  CKND0 g1754(.I (counter[1]), .ZN (n_4));
  CKND0 g1757(.I (ssn), .ZN (n_18));
  CKND0 g1755(.I (rw_bit), .ZN (n_15));
  CKND0 g1756(.I (counter[3]), .ZN (n_26));
  CKND0 g1758(.I (reset), .ZN (n_55));
  IND2D1 g2(.A1 (n_29), .B1 (n_3), .ZN (n_69));
endmodule

